title: "Scrolls & Crowns"
description: "Faunadia Wiki"
# Important for correct links; change URL to your user site:
url: "https://scrollsandcrowns.github.io"
baseurl: ""      # keep empty for user site
markdown: kramdown
plugins: []      # no plugins
